# Generated by Django 3.2.8 on 2021-10-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='users/profil.png', upload_to='users/%Y-%m-%d/'),
        ),
    ]
