# Generated by Django 3.2.8 on 2021-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattend',
            name='in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='studentattend',
            name='out_time',
            field=models.TimeField(),
        ),
    ]
