# Generated by Django 3.2.8 on 2021-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_auto_20211029_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattend',
            name='atten_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentattend',
            name='in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='studentattend',
            name='out_time',
            field=models.TimeField(),
        ),
    ]
