# Generated by Django 3.2.8 on 2021-10-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_auto_20211029_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattend',
            name='atten_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentattend',
            name='in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='studentattend',
            name='out_time',
            field=models.TimeField(),
        ),
    ]
